/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ILucide-Users': typeof import('~icons/lucide/-users')['default']
    ILucideArrowUpCircle: typeof import('~icons/lucide/arrow-up-circle')['default']
    ILucideBookOpen: typeof import('~icons/lucide/book-open')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideClock: typeof import('~icons/lucide/clock')['default']
    ILucideFolder: typeof import('~icons/lucide/folder')['default']
    ILucideHome: typeof import('~icons/lucide/home')['default']
    ILucideLogOut: typeof import('~icons/lucide/log-out')['default']
    ILucideMoreHorizontal: typeof import('~icons/lucide/more-horizontal')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSlidersHorizontal: typeof import('~icons/lucide/sliders-horizontal')['default']
    ILucideSlidersUse: typeof import('~icons/lucide/sliders-use')['default']
    ILucideSlidersUsers: typeof import('~icons/lucide/sliders-users')['default']
    ILucideSortAsc: typeof import('~icons/lucide/sort-asc')['default']
    ILucideStar: typeof import('~icons/lucide/star')['default']
    ILucideStickyNote: typeof import('~icons/lucide/sticky-note')['default']
    ILucideTrash: typeof import('~icons/lucide/trash')['default']
    ILucideUser: typeof import('~icons/lucide/user')['default']
    ILucideUsers: typeof import('~icons/lucide/users')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
